### ISSUE TITLE
Set doorbell message no longer works

### ISSUE THREAD

**Issue by gigatexel** [uilibs/uiprotect#57]
### Describe the bug

I alread posted this here (https://github.com/home-assistant/core/issues/119571) but I assume this is an upstream issue in this lib.

Bottomline is that the Doorbell G4 Pro no longer accepts text being set using the current lib. Might have something to do with the added support for Images next to Text as content for the doorbell.

### To Reproduce

Call the HA service to set the default text. Does not return any error but text is not being displayed.

### Version

core-2024.6.2

### Platform

HA OS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### No Duplicate

- [X] I have checked existing issues to avoid duplicates.

**Comment by bdraco** [comment]
Hi @gigatexel 

This library is currently looking for a primary maintainer so issues may take a while to get solved. 

I'm helping out until someone can be found. I don't have a UniFi protect doorbell so I'm not likely to be able to fix this issue.

I do have a family member with one that I'm going to visit mid next month and I'll try to replicate this issue.

In the meantime time any debugging you can do to help locate the issue would be appreciated.  If we find out what has changed in 4.x, I can probably write a fix even without physical access test device.

**Comment by gigatexel** [comment]
> Hi @gigatexel
> 
> This library is currently looking for a primary maintainer so issues may take a while to get solved.
> 
> I'm helping out until someone can be found. I don't have a UniFi protect doorbell so I'm not likely to be able to fix this issue.
> 
> I do have a family member with one that I'm going to visit mid next month and I'll try to replicate this issue.
> 
> In the meantime time any debugging you can do to help locate the issue would be appreciated. If we find out what has changed in 4.x, I can probably write a fix even without physical access test device.

Hi @bdraco. As a first, thank you for your efforts. I was aware of the situation when reading through the unifprotect-related topics in ha/core. 
While I'm not a full blown python/HA developer, I sure know my way around and I am keen to help.
I tried to get some insight in the requests/responses that are being sent to try to debug, but the config below doesn't seem to help.
Would it be easier to debug when running the lib in docker?

```
logger:
  default: warning
  logs:
    homeassistant.components.unifiprotect: info
    uiprotect: info
```

**Comment by bdraco** [comment]
If you could open developer tools in chrome/firefox/etc, and start capturing the http traffic, than change the doorbell message locally when logged into the NVR/UDMP we can compare what its doing to what the library is doing and see if we can spot the difference

**Comment by bdraco** [comment]
Didn't mean to close this one, it auto closed when the refactored code merged

**Comment by bdraco** [comment]
I did find an issue with processing events
I'll fix that shortly.  not sure if its the issue or not

**Comment by bdraco** [comment]
Its possible the last PR I merged fixed the issue.

But I have no way to know 😢

**Comment by darkrain-nl** [comment]
Is there a trick for me for example to test that?

As in can I ask Home Assistant to use the latest version?

**Comment by bdraco** [comment]
I opened a PR to HA so you can test it as a custom component with this script as soon as 1.7.1 publishes:
```
cd /config
curl -o- -sSL https://gist.githubusercontent.com/bdraco/43f8043cb04b9838383fd71353e99b18/raw/core_integration_pr | bash /dev/stdin -d unifiprotect -p 119694
```

**Comment by gigatexel** [comment]
This is the HTTP traffic when setting the default message to "datalog" (without quotes)
Rename to .har to make it readable again

[datalog.txt](https://github.com/user-attachments/files/15839588/datalog.txt)

**Comment by gigatexel** [comment]
> I opened a PR to HA so you can test it as a custom component with this script as soon as 1.7.1 publishes:
> 
> ```
> cd /config
> curl -o- -sSL https://gist.githubusercontent.com/bdraco/43f8043cb04b9838383fd71353e99b18/raw/core_integration_pr | bash /dev/stdin -d unifiprotect -p 119694
> ```

And what about adding the uniprotect integration in the custom components folder and setting the manifest to require 1.7.1?

**Comment by bdraco** [comment]
`\"defaultMessageText\":\"Test using service call\"`

It looks like its accepting the new message.

I wonder if UI has removed this functionality

**Comment by darkrain-nl** [comment]
> I opened a PR to HA so you can test it as a custom component with this script as soon as 1.7.1 publishes:
> 
> ```
> cd /config
> curl -o- -sSL https://gist.githubusercontent.com/bdraco/43f8043cb04b9838383fd71353e99b18/raw/core_integration_pr | bash /dev/stdin -d unifiprotect -p 119694
> ```

Tried it returns an error:
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 793, in handle_execute_script
    script_result = await script_obj.async_run(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1769, in async_run
    return await asyncio.shield(create_eager_task(run.async_run()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 464, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 528, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 558, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 526, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 763, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 726, in _async_run_long_action
    return await long_task
           ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2741, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2784, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/unifiprotect/services.py", line 151, in set_default_doorbell_text
    await _async_service_call_nvr(hass, call, "set_default_doorbell_message", message)
  File "/config/custom_components/unifiprotect/services.py", line 129, in _async_service_call_nvr
    await asyncio.gather(
          ^^^^^^^^^^^^^^^
  File "/config/custom_components/unifiprotect/services.py", line 130, in <genexpr>
    *(getattr(i.bootstrap.nvr, method)(*args, **kwargs) for i in instances)
              ^^^^^^^^^^^
AttributeError: 'Controller' object has no attribute 'bootstrap'
```

**Comment by bdraco** [comment]
Is there still a way to set a one off message in the protect UI?

**Comment by bdraco** [comment]
> > I opened a PR to HA so you can test it as a custom component with this script as soon as 1.7.1 publishes:
> > ```
> > cd /config
> > curl -o- -sSL https://gist.githubusercontent.com/bdraco/43f8043cb04b9838383fd71353e99b18/raw/core_integration_pr | bash /dev/stdin -d unifiprotect -p 119694
> > ```
> 
> Tried it returns an error:
> 
> ```
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
>     await func(hass, connection, msg)
>   File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 793, in handle_execute_script
>     script_result = await script_obj.async_run(
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1769, in async_run
>     return await asyncio.shield(create_eager_task(run.async_run()))
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 464, in async_run
>     await self._async_step(log_exceptions=False)
>   File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 528, in _async_step
>     self._handle_exception(
>   File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 558, in _handle_exception
>     raise exception
>   File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 526, in _async_step
>     await getattr(self, handler)()
>   File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 763, in _async_call_service_step
>     response_data = await self._async_run_long_action(
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 726, in _async_run_long_action
>     return await long_task
>            ^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/core.py", line 2741, in async_call
>     response_data = await coro
>                     ^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/core.py", line 2784, in _execute_service
>     return await target(service_call)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/unifiprotect/services.py", line 151, in set_default_doorbell_text
>     await _async_service_call_nvr(hass, call, "set_default_doorbell_message", message)
>   File "/config/custom_components/unifiprotect/services.py", line 129, in _async_service_call_nvr
>     await asyncio.gather(
>           ^^^^^^^^^^^^^^^
>   File "/config/custom_components/unifiprotect/services.py", line 130, in <genexpr>
>     *(getattr(i.bootstrap.nvr, method)(*args, **kwargs) for i in instances)
>               ^^^^^^^^^^^
> AttributeError: 'Controller' object has no attribute 'bootstrap'
> ```

It might not be compatible with the base HA version you are using.  I had tried it on `dev`. Let me try it on 2024.6.x

**Comment by darkrain-nl** [comment]
> Is there still a way to set a one off message in the protect UI?

You can add messages, but I think they may have removed the one off message capability...
![afbeelding](https://github.com/uilibs/uiprotect/assets/24763370/76be7638-7f66-4454-af04-b4aa2a95ba41)

**Comment by bdraco** [comment]
So it does look like they removed the functionality so we need to remove the service from HA

**Comment by bdraco** [comment]
I just tested it on 2024.6.2, and the script I posted only works if you have `dev`. It won't work on 2024.6.x because too much has changed.

You'd have to copy all the files from 2024.6.2 and than bump the version of uiprotect to 1.7.1 to /config/custom_components/unifiprotect instead.

But I think its moot as there isn't anything to fix since they removed the functionality

**Comment by darkrain-nl** [comment]
> I just tested it on 2024.6.2, and the script I posted only works if you have `dev`. It won't work on 2024.6.x because too much has changed.
> 
> You'd have to copy all the files from 2024.6.2 and than bump the version of uiprotect to 1.7.1 to /config/custom_components/unifiprotect instead.
> 
> But I think its moot as there isn't anything to fix since they removed the functionality

Yep looks like that, won't spend more time on it..

**Comment by bdraco** [comment]
I opened https://github.com/home-assistant/core/pull/119695 to remove the service so nobody else has to waste their time trying to getting it to work.

Thanks for reporting @gigatexel 
Thanks for testing @darkrain-nl

**Comment by zappy16** [comment]
I'm running Protect 4.0.33 with Unifi OS 4.0.5 and if I use the "Text: Set Value" on my Doorbell, it works. 
![Screenshot 2024-06-14 at 9 40 46 AM](https://github.com/uilibs/uiprotect/assets/17417763/fc4c723b-6f6b-4a34-8d5b-a0c9a52a7370)

**Comment by darkrain-nl** [comment]
> I'm running Protect 4.0.33 with Unifi OS 4.0.5 and if I use the "Text: Set Value" on my Doorbell, it works. ![Screenshot 2024-06-14 at 9 40 46 AM](https://private-user-images.githubusercontent.com/17417763/339825536-fc4c723b-6f6b-4a34-8d5b-a0c9a52a7370.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzODA5MjAsIm5iZiI6MTcxODM4MDYyMCwicGF0aCI6Ii8xNzQxNzc2My8zMzk4MjU1MzYtZmM0YzcyM2ItNmY2Yi00YTM0LThkNWItYTBjOWE1MmE3MzcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDE1NTcwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5YTgxNDFhNmNjODcyM2Q3Mjg5MGRiODQ4NmJkNjA1MWZiMTIwMWI4OWE0YzkwMTBlNjBiZTVhOWM4M2QyYjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZTRNKnjjdrIM_AkjMA24eJi_fH4gSLPJCRXTJvwkZ-4)

Aha but that is using a different service namely 'Text: Set value' and indeed, this works for me as well.

That means it still makes sense to remove the other service that was created by the integration, as this one should always be available I believe.

**Comment by gigatexel** [comment]
> > I'm running Protect 4.0.33 with Unifi OS 4.0.5 and if I use the "Text: Set Value" on my Doorbell, it works. ![Screenshot 2024-06-14 at 9 40 46 AM](https://private-user-images.githubusercontent.com/17417763/339825536-fc4c723b-6f6b-4a34-8d5b-a0c9a52a7370.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzODA5MjAsIm5iZiI6MTcxODM4MDYyMCwicGF0aCI6Ii8xNzQxNzc2My8zMzk4MjU1MzYtZmM0YzcyM2ItNmY2Yi00YTM0LThkNWItYTBjOWE1MmE3MzcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDE1NTcwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5YTgxNDFhNmNjODcyM2Q3Mjg5MGRiODQ4NmJkNjA1MWZiMTIwMWI4OWE0YzkwMTBlNjBiZTVhOWM4M2QyYjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZTRNKnjjdrIM_AkjMA24eJi_fH4gSLPJCRXTJvwkZ-4)
> 
> Aha but that is using a different service namely 'Text: Set value' and indeed, this works for me as well.
> 
> That means it still makes sense to remove the other service that was created by the integration, as this one should always be available I believe.

Works here too.
Question is, will it revert back to default value or not? And if so, after what timeout?

**Comment by zappy16** [comment]
> That means it still makes sense to remove the other service that was created by the integration, as this one should always be available I believe.

True. Just wanted to throw out what I found that works. It's been more than 30 minutes and it still showing the message I set. I'll leave it there to see how long it will show for.
